# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEditCommentTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_editCommentTest(self):
    self.driver.get("http://127.0.0.1:3000/")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
    self.driver.find_element(By.ID, "jwhfglt7l").send_keys("demo@keystonejs.com")
    self.driver.find_element(By.ID, "ig4ugx8mz").send_keys("demo")
    self.driver.find_element(By.ID, "ig4ugx8mz").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".dashboard-group__list:nth-child(2) .dashboard-group__list-label").click()
    self.driver.find_element(By.LINK_TEXT, "646c26cb394b6b0018f7ffd9").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#mceu_4 > button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.CSS_SELECTOR, "p").click()
    element = self.driver.find_element(By.ID, "tinymce")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>test 1</p>'}", element)
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, ".css-2960tt").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-2960tt")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
