# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCreateUserTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_createUserTest(self):
    self.driver.get("http://127.0.0.1:3000/")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
    self.driver.find_element(By.ID, "4j35bg1a5").send_keys("demo@keystonejs.com")
    self.driver.find_element(By.ID, "4d4a3d7k3").send_keys("demo")
    self.driver.find_element(By.ID, "4d4a3d7k3").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".dashboard-group:nth-child(4) .dashboard-group__list-label").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".css-we21er").click()
    self.driver.find_element(By.ID, "cgbq25sms").send_keys("Test")
    self.driver.find_element(By.NAME, "name.last").send_keys("User")
    self.driver.find_element(By.ID, "j3d6yuode").send_keys("test@keystonejs.com")
    self.driver.find_element(By.ID, "wbb1omy0y").send_keys("12345678*")
    self.driver.find_element(By.NAME, "password_confirm").send_keys("12345678*")
    self.driver.find_element(By.CSS_SELECTOR, ".css-h629qq").click()
    self.driver.find_element(By.CSS_SELECTOR, ".css-2960tt").click()
  
